name: treatment-ai
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  
  # Survival analysis
  - lifelines
  
  # Bioinformatics
  - pip
  - pip:
    - gseapy
    - scanpy
    - anndata
    - requests
    - tqdm
    - openpyxl